version: 0.2

env:
  secrets-manager:
    LOGIN: x23195975_SecretMan:sonartoken
    HOST: x23195975_SecretMan:HOST
    Organization: x23195975_SecretMan:Organization
    Project: x23195975_SecretMan:Project

phases:
  pre_build:
    commands:
      # Pre-build commands

  build:
    commands:
      # Print environment variables for debugging
      - echo "LOGIN=$LOGIN"
      - echo "HOST=$HOST"
      - echo "Organization=$Organization"
      - echo "Project=$Project"
      
      # Verify SonarScanner installation and path
      
      # Execute SonarScanner command

      # Display the content of the SonarScanner log file for debugging
      
      # Check the quality gate status
      - echo "Content of result.json:"
      - cat result.json || echo "Unable to read result.json file"
      - echo "Value of projectStatus.status:"
      - jq -r '.projectStatus.status' result.json || echo "Unable to extract projectStatus.status from result.json"

      # Fail the build if the quality gate status is not "OK"
      - if [ "$(jq -r '.projectStatus.status' result.json)" != "OK" ]; then
          exit 1
        fi
