# Generated by Django 2.1.15 on 2024-03-18 14:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lyricapp', '0002_auto_20240318_1441'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lyricapp',
            new_name='lyric',
        ),
    ]
